config/routes.rb
Rails.application.routes.draw do
  get 'chatmessages/index'
  namespace :admin do
    root "homes#top"
    resources :users,only: [:show, :index, :edit, :update]
    resources :posts,only: [:index,:show,:destroy]
    resources :comments,only: [:destroy]
    resources :chatgroups,only: [:index,:show,:destroy,:edit]
  end
  get 'comments/new'
  get 'comments/index'
  root :to =>"user/homes#top"


  devise_for :users,skip: [:passwords],controllers: {
    registrations: "user/registrations",
    sessions: 'user/sessions'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'user/sessions#guest_sign_in'
  end

  namespace :user do
    resources :users, only: [:show,:edit,:update] do
    get ":id/favorites" => "users#favorites",on: :collection, as: "myfavorites"
   end
    get "user/:id/unsubscribe" => "users#unsubscribe",as: "unsubscribe"
    patch "user/:id/withdraw" => "users#withdraw",as: "withdraw"

  end

  resources :posts, only: [:new,:index,:show,:create,:edit,:update,:destroy] do
      resources :comments, only: [:new,:index,:create,:destroy]
      resources :favorites, only: [:create,:destroy]
      collection do
      get 'search'
      get 'tag_search'
    end


  end

  devise_for :admins, skip: [:registrations,:passwords], controllers: {
    sessions: "admin/sessions"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :chatgroups do
    collection do
      get :join
    end
    resources :chatmessages, only: [:index,:create,:destroy]
  end

  resources :connects, only: :destroy
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!

  def create
    @post = Post.find(params[:post_id])
    favorite = current_user.favorites.new(post_id: @post.id)
    favorite.save
  end

  def destroy
    @post=Post.find(params[:post_id])
    favorite = current_user.favorites.find_by(post_id: @post.id)
    favorite.destroy
  end
end

app/helpers/user/favorites_helper.rb
module User::FavoritesHelper
end

app/views/favorites/_favorites.html.erb
<% if post.favorited_by?(current_user) %>
<%=link_to post_favorite_path(post,post.favorites),method: :delete,remote: true do %>
♥<%=post.favorites.count%>
<%end%>

<%else%>

<%=link_to post_favorites_path(post),method: :post,remote: true do %>
♡<%=post.favorites.count%>
<%end%>

<%end%>

app/views/favorites/create.js.erb
$('#favorite_buttons_<%= @post.id %>').html("<%=j(render 'favorites/favorites',post: @post)%>");

app/views/favorites/destroy.js.erb
$('#favorite_buttons_<%= @post.id %>').html("<%=j(render 'favorites/favorites',post: @post)%>");