config/routes.rb
Rails.application.routes.draw do
  get 'chatmessages/index'
  namespace :admin do
    root "homes#top"
    resources :users,only: [:show, :index, :edit, :update]
    resources :posts,only: [:index,:show,:destroy]
    resources :comments,only: [:destroy]
    resources :chatgroups,only: [:index,:show,:destroy,:edit]
  end
  get 'comments/new'
  get 'comments/index'
  root :to =>"user/homes#top"


  devise_for :users,skip: [:passwords],controllers: {
    registrations: "user/registrations",
    sessions: 'user/sessions'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'user/sessions#guest_sign_in'
  end

  namespace :user do
    resources :users, only: [:show,:edit,:update] do
    get ":id/favorites" => "users#favorites",on: :collection, as: "myfavorites"
   end
    get "user/:id/unsubscribe" => "users#unsubscribe",as: "unsubscribe"
    patch "user/:id/withdraw" => "users#withdraw",as: "withdraw"

  end

  resources :posts, only: [:new,:index,:show,:create,:edit,:update,:destroy] do
      resources :comments, only: [:new,:index,:create,:destroy]
      resources :favorites, only: [:create,:destroy]
      collection do
      get 'search'
      get 'tag_search'
    end


  end

  devise_for :admins, skip: [:registrations,:passwords], controllers: {
    sessions: "admin/sessions"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :chatgroups do
    collection do
      get :join
    end
    resources :chatmessages, only: [:index,:create,:destroy]
  end

  resources :connects, only: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts,dependent: :destroy
  has_many :comments,dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :connects
  has_many :chatgroups,through: :connects
  has_many :chatmessages,dependent: :destroy

  has_one_attached :profile_image

  validates :introduction, length: { maximum: 100 }

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  def self.guest
  find_or_create_by!(email: 'aaa@aaa.com') do |user|
    user.password = SecureRandom.urlsafe_base64
    user.password_confirmation = user.password
    user.nickname = 'ゲスト'
   end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  def index
    @users=User.page(params[:page]).per(10)
  end

  def show
    @user=User.find(params[:id])
  end

  def edit
    @user=User.find(params[:id])
  end

  def update
    @user=User.find(params[:id])
    @user.update(user_params)
    redirect_to admin_user_path
  end

  private

  def user_params
    params.require(:user).permit(:nickname,:introduction,:email,:is_deleted)
  end
end

app/controllers/user/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/guests_controller.rb
class User::GuestsController < ApplicationController

   def new_guest
     user = User.find_or_create_by!(email: 'guest@example.com') do |user|
     user.password = SecureRandom.urlsafe_base64
     # user.confirmed_at = Time.now  # Confirmable を使用している場合は必要
   end

   sign_in user
   redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
   end

end

app/controllers/user/homes_controller.rb
class User::HomesController < ApplicationController
  def top
   @user=current_user
  end
end

app/controllers/user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
   before_action :ensure_normal_user, only: [:destroy,:update,:edit]
   before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
   def configure_sign_up_params
     devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname,])
   end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
   def after_sign_up_path_for(resource)
     user_user_path(resource)
   end

   def ensure_normal_user
    if resource.email == 'aaa@aaa.com'
      redirect_to posts_path, alert: 'ゲストログインは編集・削除はできません'
    end
   end
  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  before_action :user_state, only: [:create]
  # before_action :configure_sign_in_params, only: [:create]
  def guest_sign_in
    user = User.guest
    sign_in user   # ユーザーをログインさせる
    redirect_to posts_path, notice: 'ゲストユーザーとしてログインしました。'
  end
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end


   protected
      def user_state
        @user = User.find_by(email: params[:user][:email])
        return if !@user
        if @user.valid_password?(params[:user][:password])
          if @user.is_deleted == true
            redirect_to root_path

          end
        end
      end
  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/user/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/users_controller.rb
class User::UsersController < ApplicationController
  before_action :set_user, only: [:favorites]
  before_action :not_guest_user!, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.page(params[:page]).per(10)
  end

  def edit
   @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_user_path(@user.id)
    else
      render :edit
    end
  end

  def unsubscribe
   @user = User.find(params[:id])
  end

  def withdraw
    @user = current_user
    @user.update(is_deleted: true)
    reset_session
    redirect_to root_path
  end

  def favorites
    favorite=Favorite.where(user_id: @user.id).pluck(:post_id)
    @favorites=Post.find(favorite)
  end

  private

  def user_params
    params.require(:user).permit(:nickname,:introduction,:email,:profile_image)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def not_guest_user!
    if current_user.email == "aaa@aaa.com"
      flash[:alert] = "ゲストユーザーは編集できません"
      redirect_to user_user_path(current_user)
    end
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/user/favorites_helper.rb
module User::FavoritesHelper
end

app/helpers/user/guests_helper.rb
module User::GuestsHelper
end

app/helpers/user/homes_helper.rb
module User::HomesHelper
end

app/helpers/user/users_helper.rb
module User::UsersHelper
end

app/views/user/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-4">
      <h1>ユーザー情報編集</h1>
    </div>
  </div>
      <%= form_with model: @user,url: user_user_path(@user.id),method: :put do |f| %>

  <div class="row">
    <div class="col-sm-10 offset-3">
      <table class="table-borderless-item">

        <tr>
          <div>
           <p class="my-3">
            <td><%= f.label "プロフィール画像" %></td>
            <td><%= f.file_field :profile_image, accept: "image/*" %></td>
           </p>
          </div>
        </tr>

        <tr>
          <div class="col-sm-2">
           <p class="my-3">
            <td><%= f.label "ニックネーム" %></td>
            <td><%= f.text_field :nickname %></td>
           </p>
          </div>
        </tr>

        <tr>
          <div class="col-sm-2">
           <p>
            <td><%= f.label "自己紹介文" %></td>
            <td><%= f.text_area :introduction,style: "width: 100%; height: 200px;" %></td>
           </p>
          </div>
       </tr>

       <tr>
          <div class="col-sm-2">
           <p class="my-3">
            <td><%= f.label "メールアドレス" %></td>
            <td><%= f.text_field :email,style: "width: 100%; " %></td>
           </p>
          </div>
       </tr>

      </table>
    </div>
  </div>
  <div class="row text-center mb-3">
    <div class="col-sm-12">
      <td><%= f.submit "編集内容を保存",class: "btn btn-success col-sm-2" %></td>
    </div>
     <% end %>
  </div>
  <div class="row text-center mb-3">
    <div class="col-sm-12">
      <td><%= link_to "退会",user_unsubscribe_path, class: "btn btn-danger col-sm-2"%></td>
    </div>
  </div>
  
</div>

app/views/user/users/favorites.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
   <div class="col-10 md-8 offset-md-1">
       <h1>お気に入り一覧</h1>

        <P>投稿検索</P>
        <%= form_with url: search_posts_path, local: true, method: :get do |form| %>
        <%= form.text_field :keyword %>
        <%= form.submit "検索" %>
      <% end %>
        <table class="table table-hover table-inverse">
         <thead>
          <tr>
            <th>ユーザー画像</th>
            <th>投稿者名</th>
            <th>タイトル</th>
            <th>本文</th>
            <th>コメント数</th>
            <th>いいね</th>

          </tr>
         </thead>
         <tbody>
          <% @favorites.each do |post| %>
          <tr>
            <td><%=link_to user_user_path(post.user.id) do %>
             <%= image_tag post.user.get_profile_image(80,80)%>
             <%end%>
            </td>
            <td><%=link_to user_user_path(post.user.id) do %>
             <%= post.user.nickname %>
             <%end%>
            </td>
            <td><%=link_to post.title.truncate(10),post_path(post.id)%></td>
            <td><%=link_to post.body.truncate(20)%></td>
            <td><%=link_to "#{post.comments.count}コメント",post_path(post.id)%></td>
            <td id='favorite_buttons_<%= post.id %>'>
             <%=render 'favorites/favorites',post: post%>
             </td>
          </tr>
          <%end%>
         </tbody>
        </table>
   </div>
  </div>
</div>

app/views/user/users/show.html.erb
<div class="container">




       <h1 class="my-5"><strong>ユーザー情報</strong></h1>

      <div class="row">
      <div class="col-4">
    　<%= image_tag @user.get_profile_image(250,250)%>
      <table class="table table-bordered my-5">

        <tr>
          <td class="border-dark">ニックネーム</td>
          <td class="border-dark"><%= @user.nickname %></td>
        </tr>
        <tr>
          <td class="border-dark">自己紹介文</td>
          <td class="border-dark"><%=simple_format(@user.introduction)%></td>
        </tr>
      </table>
      <div class="my-2">
       <%= link_to "いいね一覧",myfavorites_user_users_path(@user), class: "btn btn-primary" %>

       <%= link_to "編集する", edit_user_user_path(@user), class: "btn btn-success" %>
      </div>
  　</div>

   <div class="col-8">
     <table class="table table-hover table-inverse">
         <thead>
          <tr>
            <th>ユーザー画像</th>
            <th>投稿者</th>
            <th>タイトル</th>
            <th>本文</th>
            <th>コメント</th>
            <th>いいね</th>

          </tr>
         </thead>
         <tbody>
          <% @posts.each do |post| %>
          <tr>
            <td>
             <%= image_tag post.user.get_profile_image(80,80)%>

            </td>
            <td>
             <%= post.user.nickname %>

            </td>
            <td><%=link_to post.title.truncate(10),post_path(post.id)%></td>
            <td><%=link_to post.body.truncate(10),post_path(post.id)%></td>
            <td><%=link_to "#{post.comments.count}コメント",post_path(post.id)%></td>
            <td id='favorite_buttons_<%= post.id %>'>
             <%=render 'favorites/favorites',post: post%>
             </td>
          </tr>
          <%end%>
         </tbody>
        </table>
        <%= paginate @posts %>
   </div>
　</div>

  </div>

app/views/user/users/unsubscribe.html.erb
<div class="container">
  <div class="text-center mt-4">
    <h2><strong>本当に退会しますか？</strong></h2>
  </div>

  <div class="text-center mt-5 mb-5">
    <p>
      退会すると、会員登録情報や<br>
      これまでの購入履歴が閲覧できなくなります。<br>
      退会する場合は、「退会する」をクリックしてください。
    </p>
  </div>

  <div class="row justify-content-center">
    <div class="col-2"><%= link_to "退会しない", user_user_path(current_user), class: "btn btn-primary" %></div>
    <div class="col-2"><%= link_to "退会する", user_withdraw_path, method: :patch, class: "btn btn-danger", "data-confirm" => "退会しますか?" %></div>
  </div>

</div>