config/routes.rb
Rails.application.routes.draw do
  get 'chatmessages/index'
  namespace :admin do
    root "homes#top"
    resources :users,only: [:show, :index, :edit, :update]
    resources :posts,only: [:index,:show,:destroy]
    resources :comments,only: [:destroy]
    resources :chatgroups,only: [:index,:show,:destroy,:edit]
  end
  get 'comments/new'
  get 'comments/index'
  root :to =>"user/homes#top"


  devise_for :users,skip: [:passwords],controllers: {
    registrations: "user/registrations",
    sessions: 'user/sessions'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'user/sessions#guest_sign_in'
  end

  namespace :user do
    resources :users, only: [:show,:edit,:update] do
    get ":id/favorites" => "users#favorites",on: :collection, as: "myfavorites"
   end
    get "user/:id/unsubscribe" => "users#unsubscribe",as: "unsubscribe"
    patch "user/:id/withdraw" => "users#withdraw",as: "withdraw"

  end

  resources :posts, only: [:new,:index,:show,:create,:edit,:update,:destroy] do
      resources :comments, only: [:new,:index,:create,:destroy]
      resources :favorites, only: [:create,:destroy]
      collection do
      get 'search'
      get 'tag_search'
    end


  end

  devise_for :admins, skip: [:registrations,:passwords], controllers: {
    sessions: "admin/sessions"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :chatgroups do
    collection do
      get :join
    end
    resources :chatmessages, only: [:index,:create,:destroy]
  end

  resources :connects, only: :destroy
end

app/models/chatgroup.rb
class Chatgroup < ApplicationRecord
  has_many :connects, dependent: :destroy
  has_many :users, through: :connects
  has_many :chatmessages, dependent: :destroy

  has_one_attached :group_image

  def get_group_image(width, height)
    unless group_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      group_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
     group_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/admin/chatgroups_controller.rb
class Admin::ChatgroupsController < ApplicationController
  def index
    @chatgroups = Chatgroup.all
  end

  def show
    @chatgroup = Chatgroup.find(params[:id])
    @connects = @chatgroup.connects
  end

  def destroy
    @chatgroup = Chatgroup.find(params[:id])
    @chatgroup.destroy
    redirect_to admin_chatgroups_path
  end

end

app/controllers/chatgroups_controller.rb
class ChatgroupsController < ApplicationController

  def index
    @chatgroups = Chatgroup.all.order(created_at: :desc).page(params[:page]).per(10)
    @chatgroup_join = Connect.where(user_id: current_user.id)
    @nogroup = "参加しているグループはありません"
  end

  def show
    #connect =  current_user.connects.find_by(chatgroup_id: @chatgroup.id)
    #if !connect.banishd
    @chatgroup = Chatgroup.find(params[:id])
    @connects = @chatgroup.connects.page(params[:page]).per(10)
    #else
    #redirect_to root_path, alert: "you ared alredy bunishd"
    #end
  end


  def new
    @chatgroup = Chatgroup.new
  end

  def create
    @chatgroup = Chatgroup.new(chatgroup_params)
    @chatgroup.owner_id = current_user.id
      if @chatgroup.save
      redirect_to chatgroups_path, notice: 'チャットグループを作成しました'
      else
      render new,alert: 'チャットグループ作成に失敗しました'
      end
  end

  def edit
    @chatgroup = Chatgroup.find(params[:id])
  end

  def update
    if groupuser_params[:user_id].present?
       connect = Connect.new(groupuser_params)
       connect.chatgroup_id = params[:id]
       connect.save
       redirect_to chatgroup_path(params[:id])
    else
      @chatgroup = Chatgroup.find(params[:id])
      @chatgroup.update(chatgroup_params)
      redirect_to chatgroups_path
    end
  end

  #def banish
     #@chatgroup = Chatgroup.find(params[:id])
     #banish_user = User.find(params[:user_id])
     #connect = banish_user.connects.find_by(chatgroup_id: @chatgroup.id)
     #connect.update(banishd: true)
  #end

  def destroy
    @chatgroup = Chatgroup.find(params[:id])
    @chatgroup.destroy
    redirect_to chatgroups_path
  end



  def join
    @chatgroup_join = Connect.where(user_id: current_user.id)
    @nogroup = "参加しているグループはありません"
  end

  private

  def groupuser_params
    params.require(:chatgroup).permit(:user_id)
  end

  def chatgroup_params
    params.require(:chatgroup).permit(:group_name,:introduction,:group_image,user_ids: [])
  end
end

app/helpers/admin/chatgroups_helper.rb
module Admin::ChatgroupsHelper
end

app/helpers/chatgroups_helper.rb
module ChatgroupsHelper
end

app/views/admin/chatgroups/edit.html.erb
<h1>Admin::Chatgroups#edit</h1>
<p>Find me in app/views/admin/chatgroups/edit.html.erb</p>

app/views/admin/chatgroups/index.html.erb
<h4 class="my-5">チャットグループ一覧</h4>

<table class="table table-hover table-inverse">
  <thead>
    <th>グループ画像</th>
    <th>ルーム名</th>
    <th>ルーム概要</th>
    <th>参加人数</th>
  </thead>
  <tbody>
  <% @chatgroups.each do |group| %>
    <tr>
      <td><%=link_to admin_chatgroup_path(group.id) do %>
        <%=image_tag group.get_group_image(100,100)%>
        <%end%>
      </td>
      <td><%=link_to admin_chatgroup_path(group.id) do %>
        <%=group.group_name.truncate(10)%>
        <%end%>
      </td>
      <td><%=link_to admin_chatgroup_path(group.id) do %>
        <%=group.introduction.truncate(20)%>
        <%end%>
      </td>
      <td>(<%=group.user_ids.count%>)</td>
      <td><%=link_to "削除",admin_chatgroup_path(group),method: :delete, class: "btn btn-danger" %></td>
    </tr>
    <%end%>
  </tbody>
</table>

app/views/admin/chatgroups/show.html.erb
<div class="container">
 <h1><%=@chatgroup.group_name %></h1>
 <div class="row">
  <div class="col-5">
    <%= image_tag @chatgroup.get_group_image(300,300)%>
   <table class="table table-bordered mt-3">
     <tr>
       <td class="border-dark">グループ概要</td>
       <td class="border-dark"><%= @chatgroup.introduction %></td>
    </tr>
   </table>

  </div>
  <div class="col-7">
   <h3>参加しているユーザー</h3>
   <table class="table table-hover table-inverse">
     <thead>
       <tr>
         <td>ユーザー画像</td>
         <td>ユーザー名</td>
       </tr>
     </thead>
     <tbody>
      <% @connects.each do |connect|%>
        <tr>
          <td>
            <%=link_to user_user_path(connect.user.id) do %>
            <%= image_tag connect.user.get_profile_image(80,80)%>
             <%end%>
          </td>
          <td>
            <%=link_to user_user_path(connect.user.id) do %>
            <%= connect.user.nickname %>
            <%end%>
          </td>
        </tr>
      <% end %>
     </tbody>
    </table>
  </div>
 </div>
</div>